version: 2
jobs:
  buildlinuxclang:
    docker:
      - image: ubuntu:trusty
    steps:
      - checkout
      - run:
          name: Build Linux with clang
          command: USE_CURL=1 sh ci/linux.sh clang_build
      - store_artifacts:
          path: build/output/libNFHTTP.zip
          destination: libNFHTTP.zip
  buildmac:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run:
          name: Build OSX
          command: USE_CURL=1 sh ci/osx.sh build
      - store_artifacts:
          path: build/output/libNFHTTP.zip
          destination: libNFHTTP.zip
  buildmacios:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run:
          name: Build iOS
          command: BUILD_IOS=1 USE_CURL=1 sh ci/osx.sh build
      - store_artifacts:
          path: build/output/libNFHTTP.zip
          destination: libNFHTTP.zip
  buildmacandroid:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run:
          name: Build Android
          command: BUILD_ANDROID=1 USE_CURL=1 sh ci/osx.sh build
      - store_artifacts:
          path: libNFHTTP-androidx86.zip
          destination: libNFHTTP-androidx86.zip
      - store_artifacts:
          path: libNFHTTP-androidArm64.zip
          destination: libNFHTTP-androidArm64.zip
workflows:
  version: 2
  build:
    jobs:
      - buildlinuxclang
      - buildmac
      - buildmacios
      - buildmacandroid
